import { useEffect, useState } from "react";
import { Alert, Button, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, Typography } from "@mui/material";
import type { AdminInvoiceDto } from "@vega/domain";
export function InvoicesPage({ archived = false, navigate }: { archived?: boolean; navigate: (path: string) => void }) {
  const [items, setItems] = useState<AdminInvoiceDto[]>([]); const [error, setError] = useState("");
  const load = () => void fetch(`/api/admin/invoices?archived=${archived}`).then(async (r) => ({ r, b: await r.json() as { data?: { items?: AdminInvoiceDto[] } } })).then(({ r, b }) => { if (!r.ok || !b.data?.items) setError("Rechnungen konnten nicht geladen werden."); else setItems(b.data.items); }).catch(() => setError("Rechnungen konnten nicht geladen werden."));
  useEffect(load, [archived]);
  async function archive(id: string) { await fetch(`/api/admin/invoices/${id}/${archived ? "restore" : "archive"}`, { method: "POST" }); load(); }
  return <Stack spacing={2}><Stack direction="row" sx={{ justifyContent: "space-between" }}><Typography component="h1" variant="h4">{archived ? "Archivierte Rechnungen" : "Rechnungen"}</Typography>{!archived && <Button variant="contained" onClick={() => navigate("/invoices/new")}>Neue Rechnung</Button>}</Stack>{error && <Alert severity="error">{error}</Alert>}<Paper variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>Nummer</TableCell><TableCell>Kunde</TableCell><TableCell>Auftrag</TableCell><TableCell>Datum</TableCell><TableCell /></TableRow></TableHead><TableBody>{items.map((invoice) => <TableRow key={invoice.id}><TableCell><Button onClick={() => navigate(`/invoices/${invoice.id}`)}>{invoice.invoiceNumber}</Button></TableCell><TableCell>{invoice.customerName}</TableCell><TableCell>{invoice.orderNumber ?? "–"}</TableCell><TableCell>{new Date(`${invoice.invoiceDate}T00:00:00`).toLocaleDateString("de-DE")}</TableCell><TableCell><Button size="small" onClick={() => void archive(invoice.id)}>{archived ? "Wiederherstellen" : "Archivieren"}</Button></TableCell></TableRow>)}{items.length === 0 && <TableRow><TableCell colSpan={5} align="center">Keine Rechnungen vorhanden.</TableCell></TableRow>}</TableBody></Table></Paper></Stack>;
}
